# eks-db.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: db-sc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: eks-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-db
  template:
    metadata:
      labels:
        app: eks-db
    spec:
      containers:
        - name: db-container
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8s12345
            - name: MYSQL_DATABASE
              value: app
            - name: MYSQL_USER
              value: app
            - name: MYSQL_PASSWORD
              value: app12345
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-claim
